export const skills = {
  any: {
    acrobatics: { name: "Acrobatics" },
    animalHandling: { name: "Animal Handling" },
    arcana: { name: "Arcana" },
    athletics: { name: "Athletics" },
    deception: { name: "Deception" },
    history: { name: "History" },
    insight: { name: "Insight" },
    intimidation: { name: "Intimidation" },
    investigation: { name: "Investigation" },
    medicine: { name: "Medicine" },
    nature: { name: "Nature" },
    perception: { name: "Perception" },
    performance: { name: "Performance" },
    persuasion: { name: "Persuasion" },
    religion: { name: "Religion" },
    sleightOfHand: { name: "Sleight of Hand" },
    stealth: { name: "Stealth" },
    survival: { name: "Survival" },
  },
};
export const races = {
  dwarf: {
    name: "Dwarf",
    statBonuses: { CON: 2, WIS: 1 },
    speed: 25,
    profeciencies: [],
    traits: [
      {
        index: "darkvision",
        name: "Darkvision",
        url: "/api/traits/darkvision",
      },
      {
        index: "dwarven-combat-training",
        name: "Dwarven Combat Training",
        url: "/api/traits/dwarven-combat-training",
      },
      {
        index: "dwarven-resilience",
        name: "Dwarven Resilience",
        url: "/api/traits/dwarven-resilience",
      },
      {
        index: "dwarven-toughness",
        name: "Dwarven Toughness",
        url: "/api/traits/dwarven-toughness",
      },
    ],
    // subraces: {
    //   choose: 1,
    //   from: [
    //     {
    //       index: "hill-dwarf",
    //       name: "Hill Dwarf",
    //       statBonuses: { WIS: 1 },
    //       traits: [
    //         {
    //           index: "dwarven-toughness",
    //           name: "Dwarven Toughness",
    //           url: "/api/traits/dwarven-toughness",
    //         },
    //       ],
    //     },
    //     {
    //       index: "mounain-dwarf",
    //       statBonuses: { STR: 2 },
    //       traits: [
    //         {
    //           //! add later?
    //           //Dwarven armor training
    //         },
    //       ],
    //     },
    //   ],
    // },
  },

  elf: {
    name: "Elf",
    statBonuses: { DEX: 2, INT: 1 },
    speed: 30,
    traits: [
      {
        index: "darkvision",
        name: "Darkvision",
        url: "/api/traits/darkvision",
      },
      {
        index: "keen-senses",
        name: "Keen Senses",
        url: "/api/traits/keen-senses",
      },
      {
        index: "fey-ancestry",
        name: "Fey Ancestry",
        url: "/api/traits/fey-ancestry",
      },
      {
        index: "elf-weapon-training",
        name: "Elf Weapon Training",
        url: "/api/traits/elf-weapon-training",
      },
      {
        index: "extra-language",
        name: "Extra Language",
        url: "/api/traits/extra-language",
      },
      {
        //! add later?
        //! cantrip
      },
    ],
    // subraces: {
    //   choose: 1,
    //   from: [
    //     {
    //       index: "high-elf",
    //       name: "High Elf",
    //       statBonuses: { INT: 1 },
    //       traits: [
    //         {
    //           index: "elf-weapon-training",
    //           name: "Elf Weapon Training",
    //           url: "/api/traits/elf-weapon-training",
    //         },
    //         {
    //           index: "extra-language",
    //           name: "Extra Language",
    //           url: "/api/traits/extra-language",
    //         },
    //         {
    //           //! add later?
    //           //! cantrip
    //         },
    //       ],
    //     },
    //     {
    //       index: "wood-elf",
    //       name: "Wood Elf",
    //       statBonuses: { WIS: 1 },
    //       traits: [
    //         {
    //           index: "elf-weapon-training",
    //           name: "Elf Weapon Training",
    //           url: "/api/traits/elf-weapon-training",
    //         },
    //         //! add later?
    //         // traits: {
    //         //   Fleet_of_foot: "Fleet of Foot",
    //         //   Mask_of_the_wild: "Mask of the Wild",
    //         // },
    //       ],
    //     },
    //     {
    //       index: "drow",
    //       name: "Drow",
    //       statBonuses: { CHA: 1 },
    //       traits: [
    //         //! add later
    //         // superior_darkvision: "Superior Darkvision.",
    //         // sunlight_sensitivity: "Sunlight Sensitivity",
    //         // drow_magic: "Drow Magic",
    //         // drow_weapon_training: "Drow Weapon Training",
    //       ],
    //     },
    //   ],
    // },
  },

  halfling: {
    name: "Halfling",
    statBonuses: { DEX: 2, CHA: 1 },
    speed: 25,
    traits: [
      {
        index: "lucky",
        name: "Lucky",
        url: "/api/traits/lucky",
      },
      {
        index: "brave",
        name: "Brave",
        url: "/api/traits/brave",
      },
      {
        index: "halfling-nimbleness",
        name: "Halfling Nimbleness",
        url: "/api/traits/halfling-nimbleness",
      },
      {
        index: "naturally-stealthy",
        name: "Naturally Stealthy",
        url: "/api/traits/naturally-stealthy",
      },
    ],

    // subraces: {
    //   stout_halfling: {
    //     statBonuses: { CON: 1 },
    //     traits: [
    //       {
    //         index: "naturally-stealthy",
    //         name: "Naturally Stealthy",
    //         url: "/api/traits/naturally-stealthy",
    //       },
    //     ],
    //   },
    //   lightfoot_halfling: {
    //     statBonuses: { CHA: 1 },
    //     traits: { stout_resilience: "Stout Resilience" },
    //   },
    // },
  },
  human: {
    statbonuses: { STR: 1, DEX: 1, CON: 1, INT: 1, WIS: 1, CHA: 1, speed: 30 },
  },

  dragonborn: {
    name: "Dragonborn",
    statBonuses: { STR: 2, CHA: 1 },
    speed: 30,
    traits: [
      {
        index: "breath-weapon",
        name: "Breath Weapon",
        url: "/api/traits/breath-weapon",
      },
      {
        index: "draconic-ancestry",
        name: "Draconic Ancestry",
        url: "/api/traits/draconic-ancestry",
      },
      {
        //! add later?
        //damage resist
      },
    ],
  },

  gnome: {
    name: "Gnome",
    statBonuses: { INT: 2, CON: 1 },
    traits: [
      {
        index: "darkvision",
        name: "Darkvision",
        url: "/api/traits/darkvision",
      },
      {
        index: "gnome-cunning",
        name: "Gnome Cunning",
        url: "/api/traits/gnome-cunning",
      },
      {
        index: "artificers-lore",
        name: "Artificer's Lore",
        url: "/api/traits/artificers-lore",
      },
      {
        index: "tinker",
        name: "Tinker",
        url: "/api/traits/tinker",
      },
    ],
    // subraces: {
    //   forest_gnome: {
    //     statBonuses: { DEX: 2 },
    //     traits: { artificers_lore: "Artificer’s Lore", tinker: "tinker" },
    //   },
    //   rock_gnome: {
    //     statBonuses: { CON: 1 },
    //     traits: { artificers_lore: "Artificer’s Lore", tinker: "tinker" },
    //   },
    // },
  },

  half_elf: {
    name: "Half Elf",
    statBonuses: { CHA: 2 },
    chooseStats: 2,
    speed: 30,
    traits: [
      {
        index: "darkvision",
        name: "Darkvision",
        url: "/api/traits/darkvision",
      },
    ],
  },
  half_orc: {
    statBonuses: { STR: 2, CON: 2 },
    speed: 30,
    traits: [
      {
        index: "menacing",
        name: "Menacing",
        url: "/api/traits/menacing",
      },
      {
        index: "darkvision",
        name: "Darkvision",
        url: "/api/traits/darkvision",
      },
      {
        index: "relentless-endurance",
        name: "Relentless Endurance",
        url: "/api/traits/relentless-endurance",
      },
    ],
  },
  tiefling: {
    name: "Tiefling",
    statBonuses: { INT: 1, CHA: 2 },
    speed: 30,
    traits: [
      {
        index: "darkvision",
        name: "Darkvision",
        url: "/api/traits/darkvision",
      },
      {
        index: "hellish-resistance",
        name: "Hellish Resistance",
        url: "/api/traits/hellish-resistance",
      },
      {
        index: "infernal-legacy",
        name: "Infernal Legacy",
        url: "/api/traits/infernal-legacy",
      },
    ],
  },
};

export const backgrounds = [
  {
    name: "Acolyte",
    skillProficiencies: ["Insight", "Religion"],
    languages: { choose: 2 },
  },
  {
    name: "Charlatan",
    skillProficiencies: ["Deception", "Sleight of hand"],
    tool_prof: { disguise_kit: "Disguise_kit", forgery_kit: "Forgery kit" },
  },

  {
    name: "Criminal",
    skillProficiencies: ["Deception", "Stealth"],
    tool_prof: { gaming_set: { choose: 1 }, thieves_tools: "Thieves' Tools" },
  },
  {
    name: "Entertainer",
    skillProficiencies: ["Acrobatics", "Performance"],
    tool_prof: { disguise_kit: "Disguise Kit", instrument: { choose: 1 } },
  },
  {
    name: "Folk Hero",
    skillProficiencies: ["Animal Handling", "Survival"],
    tool_prof: { artisan_tools: { choose: 1 }, vehicles: "Vehicles(land)" },
  },
  {
    name: "Guild Artisan",
    skillProficiencies: ["Insight", "Persuasion"],
    tool_prof: { artisan_tools: { choose: 1 } },
    languages: { choose: 1 },
  },
  {
    name: "Hermit",
    skillProficiencies: ["Medicine", "Religion"],
    tool_prof: { herbalism_kit: "Herbalism Kit" },
    languages: { choose: 1 },
  },
  {
    name: "Noble",
    skillProficiencies: ["History", "Persuasion"],
    tool_prof: { gaming_set: { choose: 1 }, languages: { choose: 1 } },
  },
  {
    name: "Outlander",
    skillProficiencies: ["Athletics", "Survival"],
    tool_prof: { instrument: { choose: 1 } },
    languages: { choose: 1 },
  },
  {
    name: "Sage",
    skillProficiencies: ["Arcana", "Survival"],
    tool_prof: { instrument: { choose: 1 } },
    languages: { choose: 1 },
  },
  {
    name: "Sailor",
    skillProficiencies: ["Athletics", "Perception"],
    tool_prof: {
      navigators_tools: "Navigator's tools",
      water_vehicles: "Vehicles(water)",
    },
  },
  {
    name: "Soldier",
    skillProficiencies: ["Athletics", "Intimidation"],
    tool_prof: { gaming_set: { choose: 1 }, land_vehicles: "Land Vehicles" },
  },
  {
    name: "Urchin",
    skillProficiencies: ["Sleight of Hand", "Stealth"],
    tool_prof: {
      disguise_kit: "Disguise Kit",
      thieves_tools: "Thieves' Tools",
    },
  },
];

export const armors = {
  padded: {
    armorType: "light_armor",
    armorName: "Padded Armor",
    index: "padded",
  },
  leather: {
    armorType: "light_armor",
    armorName: "Leather Armor",
    index: "leather",
  },
  studded: {
    armorType: "light_armor",
    armorName: "Studded Leather",
    index: "leather",
  },
  hide: { armorType: "medium_armor", armorName: "Hide", index: "hide" },
  chainShirt: {
    armorType: "medium_armor",
    armorName: "Chain Shirt",
    index: "chain_shirt",
  },
  scaleMail: {
    armorType: "medium_armor",
    armorName: "Scale Mail",
    index: "scale_mail",
  },
  breastPlate: {
    armorType: "medium_armor",
    armorName: "Breast Plate",
    index: "breast_plate",
  },
  halfPlate: {
    armorType: "medium_armor",
    armorName: "Half Plate",
    index: "half_plate",
  },
  ringMail: {
    armorType: "heavy_armor",
    armorName: "Ring Mail",
    index: "ring_mail",
  },
  chainMail: {
    armorType: "heavy_armor",
    armorName: "Chain Mail",
    index: "chain_mail",
  },
  splint: { armorType: "heavy_armor", armorName: "Splint", index: "splint" },
  plate: { armorType: "heavy_armor", armorName: "Plate", index: "plate" },
};
export const weapons = {
  simple_weapons: {
    club: {
      equip_type: "Weapon",
      name: "Club",
      damage: 4,
      damage_type: "Bludgeoning",
      properties: ["Light"],
    },
    dagger: {
      equip_type: "Weapon",
      name: "Dagger",
      damage: 4,
      damage_type: "Piercing",
      properties: ["Light", "Finesse", "Thrown"],
    },
    greatClub: {
      equip_type: "Weapon",
      name: "Greatclub",
      damage: 8,
      damage_type: "Bludgeoning",
      properties: ["Two-handed"],
    },
    handAxe: {
      equip_type: "Weapon",
      name: "Handaxe",
      damage: 6,
      damage_type: "Slashing",
      properties: ["Light", "Thrown"],
    },
    javelin: {
      equip_type: "Weapon",
      name: "Javelin",
      damage: 6,
      damage_type: "Piercing",
      properties: ["Thrown"],
    },
    lightHammer: {
      equip_type: "Weapon",
      name: "Light Hammer",
      damage: 4,
      damage_type: "Bludgeoning",
      properties: ["Light", "Thrown"],
    },
    mace: {
      equip_type: "Weapon",
      name: "Mace",
      damage: 6,
      damage_type: "Bludgeoning",
      properties: [],
    },
    quarterstaff: {
      equip_type: "Weapon",
      name: "Quarterstaff",
      damage: 6,
      damage_type: "Bludgeoning",
      properties: ["Versatile"],
    },
    sickle: {
      equip_type: "Weapon",
      name: "Sickle",
      damage: 4,
      damage_type: "Slashing",
      properties: ["Light"],
    },
    spear: {
      equip_type: "Weapon",
      name: "Spear",
      damage: 6,
      damage_type: "Piercing",
      properties: ["Thrown", "Versatile"],
    },
  },
  simple_ranged: {
    lightCrossbow: {
      equip_type: "Weapon",
      name: "Light Crossbow",
      damage: 8,
      damage_type: "Piercing",
      properties: ["Ammunition"],
    },
    dart: {
      equip_type: "Weapon",
      name: "Dart",
      damage: 4,
      damage_type: "Piercing",
      properties: ["Finesse", "Thrown"],
    },
    shortbow: {
      equip_type: "Weapon",
      name: "Shortbow",
      damage: 6,
      damage_type: "Piercing",
      properties: ["Ammunition"],
    },
    sling: {
      equip_type: "Weapon",
      name: "Sling",
      damage: 4,
      damage_type: "Bludgeoning",
      properties: ["Ammunition"],
    },
  },
  martial_weapons: {
    battleaxe: {
      equip_type: "Weapon",
      name: "Battleaxe",
      damage: 8,
      damage_type: "Slashing",
      properties: ["Versatile"],
    },
    flail: {
      equip_type: "Weapon",
      name: "Flail",
      damage: 8,
      damage_type: "Bludgeoning",
      properties: [],
    },
    glaive: {
      equip_type: "Weapon",
      name: "Glaive",
      damage: 10,
      damage_type: "Slashing",
      properties: ["Heavy", "Reach", "Two-handed"],
    },
    greataxe: {
      equip_type: "Weapon",
      name: "Greataxe",
      damage: 12,
      damage_type: "Slashing",
      properties: ["Ammunition"],
    },
    halberd: {
      equip_type: "Weapon",
      name: "Halberd",
      damage: 10,
      damage_type: "Slashing",
      properties: ["Heavy", "Reach", "Two-handed"],
    },
    lance: {
      equip_type: "Weapon",
      name: "Lance",
      damage: 12,
      damage_type: "Piercing",
      properties: ["Special", "Reach"],
    },
    longsword: {
      equip_type: "Weapon",
      name: "Longsword",
      damage: 8,
      damage_type: "Slashing",
      properties: ["Versatile"],
    },
    maul: {
      equip_type: "Weapon",
      name: "Maul",
      damage: 12,
      damage_type: "Bludgeoning",
      properties: ["Heavy", "Two-handed"],
    },
    morningstar: {
      equip_type: "Weapon",
      name: "Morningstar",
      damage: 8,
      damage_type: "Slashing",
      properties: [],
    },
    pike: {
      equip_type: "Weapon",
      name: "Pike",
      damage: 10,
      damage_type: "Piercing",
      properties: ["Heavy", "Reach", "Two-handed"],
    },
    rapier: {
      equip_type: "Weapon",
      name: "Rapier",
      damage: 8,
      damage_type: "Piercing",
      properties: ["Finesse"],
    },
    scimitar: {
      equip_type: "Weapon",
      name: "Scimitar",
      damage: 6,
      damage_type: "Slashing",
      properties: ["Finesse", "Light"],
    },
    shortsword: {
      equip_type: "Weapon",
      name: "Shortsword",
      damage: 6,
      damage_type: "Piercing",
      properties: ["Finesse", "Light"],
    },
    trident: {
      equip_type: "Weapon",
      name: "Trident",
      damage: 6,
      damage_type: "Piercing",
      properties: ["Thrown", "Versatile"],
    },
    warPick: {
      equip_type: "Weapon",
      name: "War Pick",
      damage: 8,
      damage_type: "Piercing",
      properties: [],
    },
    warHammer: {
      equip_type: "Weapon",
      name: "Warhammer",
      damage: 8,
      damage_type: "Bludgeoning",
      properties: ["Versatile"],
    },
    whip: {
      equip_type: "Weapon",
      name: "Whip",
      damage: 4,
      damage_type: "Slashing",
      properties: ["Finesse", "Reach"],
    },
  },
  martial_ranged: {
    blowgun: {
      equip_type: "Weapon",
      name: "Blowgun",
      damage: 1,
      damage_type: "Piercing",
      properties: [],
    },
    handCrossbow: {
      equip_type: "Weapon",
      name: "Hand Crossbow",
      damage: 6,
      damage_type: "Piercing",
      properties: ["Light", "Loading"],
    },
    heavyCrossbow: {
      equip_type: "Weapon",
      name: "Heavy Crossbow",
      damage: 10,
      damage_type: "Piercing",
      properties: ["Heavy", "Loading", "Two-handed"],
    },
    longbow: {
      equip_type: "Weapon",
      name: "Longbow",
      damage: 8,
      damage_type: "Piercing",
      properties: ["Heavy", "Loading", "Two-handed"],
    },
  },
};

export const spells = {
  acidSplash: {
    name: "Acid Splash",
    time: "1 Action",
    range: 60,
    type: "attack-save",
    save: "DEX",
    damage: 6,
    duration: "Instant",
    index: "acid-splash",
  },
  alarm: {
    index: "alarm",
    name: "Alarm",
    time: "1 Munute",
    range: 30,
    type: "utility",
    damage: null,
    duration: "8 hours",
  },
  animalFriendship: {
    index: "animal-friendship",
    name: "Animal Friendship",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "24 hours",
  },
  // armorOfAgathys: {
  //   name: "Armor of Agythys",
  //   time: "1 Action",
  //   range: "Self",
  //   type: "utility",
  //   damage: null,
  //   duration: "1 hour",
  // },
  // armsOfHadar: {
  //   name: "Arms of Hadar",
  //   time: "1 Action",
  //   range: "Self",
  //   type: "attack-save",
  //   damage: 12,
  //   save: "STR",
  //   duration: "Instant",
  // },
  bane: {
    index: "bane",
    name: "Bane",
    time: "1 Action",
    range: 30,
    type: "util-save",
    save: "CHA",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  // bladeWard: {

  //   name: "Blade Ward",
  //   time: "1 Action",
  //   range: "Self",
  //   type: "utility",
  //   damage: null,
  //   duration: "1 Round",
  // },
  bless: {
    index: "bless",
    name: "Bless",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  burningHands: {
    index: "burning-hands",
    name: "Burning Hands",
    time: "1 Action",
    range: "Self",
    type: "attack-save",
    save: "DEX",
    damage: 18,
    duration: "Instant",
  },
  charmPerson: {
    index: "charm-person",
    name: "Charm Person",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "1 Hour",
  },
  chillTouch: {
    index: "chill-touch",
    name: "Chill Touch",
    time: "1 Action",
    range: 120,
    type: "attack-save",
    damage: 8,
    duration: "Instant",
  },
  // chromaticOrb: {

  //   name: "Chromatic Orb",
  //   time: "1 Action",
  //   range: 90,
  //   type: "attack",
  //   damage: 24,
  //   duration: "Instant",
  // },
  colorSpray: {
    index: "color-spray",
    name: "Color Spray",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "1 Round",
  },
  command: {
    index: "command",
    name: "Command",
    time: "1 Action",
    range: 60,
    type: "utility",
    damage: null,
    duration: "1 Round",
  },
  // compelledDuel: {

  //   name: "Compelled Duel",
  //   time: "1 Bonus Action",
  //   range: 30,
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  comprehendLanguages: {
    index: "comprehend-languages",
    name: "Comprehend Languages",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  createOrDestroyWater: {
    index: "create-or-destroy-water",
    name: "Create or Destroy Water",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  cureWounds: {
    index: "cure-wounds",
    name: "Cure Wounds",
    time: "1 Action",
    range: "Touch",
    type: "healing",
    cure: 8,
    duration: "Instant",
  },
  dancingLights: {
    index: "dancing-lights",
    name: "Dancing Lights",
    time: "1 Action",
    range: 120,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  detectEvilAndGood: {
    index: "detect-evil-and-good",
    name: "Detect Evil and Good",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  detectMagic: {
    index: "detect-magic",
    name: "Detect Magic",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  detectPoisonAndDisease: {
    index: "detect-poison-and-disease",
    name: "Detect Poison and Disease",
    time: "1 Action",
    range: "self",
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  disguiseSelf: {
    index: "disguise-self",
    name: "Disguise Self",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "1 Hour",
  },
  // dissonantWhispers: {

  //   name: "Dissonant Whispers",
  //   time: "1 action",
  //   range: 60,
  //   type: "attack-save",
  //   save: "WIS",
  //   damage: 18,
  //   duration: "Instant",
  // },
  divineFavor: {
    index: "divine-favor",
    name: "Divine Favor",
    time: "1 Bonus Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  druidcraft: {
    index: "druidcraft",
    name: "Druidcraft",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  eldritchBlast: {
    index: "eldritch-blast",
    name: "Eldritch Blast",
    time: "1 Action",
    range: 120,
    type: "attack",
    damage: 10,
    duration: "Instant",
  },
  // ensnaringStrike: {

  //   name: "Ensnaring Strike",
  //   time: "1 Bonus Action",
  //   range: "Self",
  //   type: "utility-save",
  //   save: "STR",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  entangle: {
    index: "entangle",
    name: "Entangle",
    time: "1 Action",
    range: 90,
    type: "utility-save",
    save: "STR",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  expeditiousRetreat: {
    index: "expeditious-retreat",
    name: "Expeditious Retreat",
    time: "1 Bonus Action",
    range: 90,
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  faerieFire: {
    index: "faerie-fire",
    name: "Faerie Fire",
    time: "1 Action",
    range: 60,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  falseLife: {
    index: "false-life",
    name: "False Life",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "1 Hour",
  },
  featherFall: {
    index: "feather-fall",
    name: "Feather Fall",
    time: "1 Reaction",
    range: 60,
    type: "utility",
    damage: null,
    duration: "1 Minute",
  },
  findFamiliar: {
    index: "find-familiar",
    name: "Find Familiar",
    time: "1 Hour",
    range: 10,
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  fireBolt: {
    index: "fire-bolt",
    name: "Fire Bolt",
    time: "1 Action",
    range: 120,
    type: "attack",
    damage: 10,
    duration: "Instant",
  },
  fogCloud: {
    index: "fog-cloud",
    name: "Fog Cloud",
    time: "1 Action",
    range: 120,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 hour",
  },
  // friends: {

  //   name: "Friends",
  //   time: "1 Action",
  //   range: "Self",
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  goodBerry: {
    index: "goodberry",
    name: "Goodberry",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  grease: {
    index: "grease",
    name: "Grease",
    time: "1 Action",
    range: 60,
    type: "utility-save",
    save: "DEX",
    damage: null,
    duration: "1 Minute",
  },
  guidance: {
    index: "guidance",
    name: "Guidance",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  guidingBolt: {
    index: "guiding-bolt",
    name: "Guiding Bolt",
    time: "1 Action",
    range: 120,
    type: "attack",
    damage: 24,
    duration: "1 Round",
  },
  // hailOfThorns: {

  //   name: "Hail of Thorns",
  //   time: "1 Bonus Action",
  //   range: "Self",
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  healingWord: {
    index: "healing-word",
    name: "Healing Word",
    time: "1 Bonus Action",
    range: 60,
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  hellishRebuke: {
    index: "hellish-rebuke",
    name: "Hellish Rebuke",
    time: "1 Reaction",
    range: 60,
    type: "attack-save",
    save: "DEX",
    damage: 20,
    duration: "Instant",
  },
  heroism: {
    index: "heroism",
    name: "Heroism",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  // hex: {

  //   name: "Hex",
  //   time: "1 Bonus Action",
  //   range: 90,
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 hour",
  // },
  huntersMark: {
    index: "hunters-mark",
    name: "Hunter's Mark",
    time: "1 Bonus Action",
    range: 90,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 hour",
  },
  inflictWounds: {
    index: "inflict-wounds",
    name: " Inflict Wounds",
    time: "1 Action",
    range: "Touch",
    type: "attack",
    damage: 30,
    duration: "Instant",
  },
  identify: {
    index: "identify",
    name: "Identify",
    time: "1 Minute",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  illusoryScript: {
    index: "illusory-script",
    name: "Illusory Script",
    time: "1 Minute",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "10 Days",
  },
  jump: {
    index: "jump",
    name: "Jump",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "1 Minute",
  },
  light: {
    index: "light",
    name: "Light",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "1 Hour",
  },
  longStrider: {
    index: "longstrider",
    name: "Longstrider",
    time: "1 action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  mageArmor: {
    index: "mage-armor",
    name: "Mage Armor",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "8 Hours",
  },
  mageHand: {
    index: "mage-hand",
    name: "Mage Hand",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "1 Minute",
  },
  magicMissile: {
    index: "magic-missile",
    name: "Magic Missile",
    time: "1 Action",
    range: 120,
    type: "attack",
    damage: 5,
    duration: "Instant",
  },
  mending: {
    index: "mending",
    name: "Mending",
    time: "1 Minute",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  message: {
    index: "message",
    name: "Message",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "1 Round",
  },
  minorIllusion: {
    index: "minor-illusion",
    name: "Minor Illusion",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "1 Minute",
  },
  poisonSpray: {
    index: "poison-spray",
    name: "Poison Spray",
    time: "1 Action",
    range: 10,
    type: "attack-save",
    save: "CON",
    damage: 12,
    duration: "Instant",
  },
  prestidigitation: {
    index: "prestidigitation",
    name: "Prestidigitation",
    time: "1 Action",
    range: 10,
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  produceFlame: {
    index: "produce-flame",
    name: "Produce Flame",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "10 minutes",
  },
  protectionFromEvilAndGood: {
    index: "protection-from-evil-and-good",
    name: "Protection From Evil and Good",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  purifyFoodAndDrink: {
    index: "purify-food-and-drink",
    name: "Purify Food and Drink",
    time: "1 Action",
    range: 10,
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  rayOfFrost: {
    index: "ray-of-frost",
    name: "Ray of Frost",
    time: "1 Action",
    range: 60,
    type: "attack",
    damage: 8,
    duration: "Instant",
  },
  // rayOfSickness: {

  //   name: "Ray of Sickness",
  //   time: "1 Action",
  //   range: 60,
  //   type: "attack",
  //   damage: 16,
  //   duration: "Instant",
  // },
  // resistance: {
  //   name: "Resistance",
  //   time: "1 Action",
  //   range: "Touch",
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  sacredFlame: {
    index: "sacred-flame",
    name: "Sacred Flame",
    time: "1 Action",
    range: 60,
    type: "attck-save",
    save: "DEX",
    damage: 8,
    duration: "Instant",
  },
  sanctuary: {
    index: "sanctuary",
    name: "Sanctuary",
    time: "1 Bonus Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "1 Minute",
  },
  // searingSmite: {
  //   name: "Searing Smite",
  //   time: "1 Bonus Action",
  //   range: "Self",
  //   type: "Utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  shield: {
    index: "shield",
    name: "Shield",
    time: "1 Reaction",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "1 Round",
  },

  shieldOfFaith: {
    index: "shield-of-faith",
    name: "Shield of Faith",
    time: "1 Bonus Action",
    range: 60,
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  shillelagh: {
    index: "shillelagh",
    name: "Shillelagh",
    time: "1 Bonus Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "1 Munute",
  },
  shockingGrasp: {
    index: "shocking-grasp",
    name: "Shocking Grasp",
    time: "1 Action",
    range: "Touch",
    type: "attack",
    damage: 8,
    duration: "Instant",
  },
  silentImage: {
    index: "silent-image",
    name: "Silent Image",
    time: "1 Action",
    range: 60,
    type: "utility",
    damage: null,
    duration: "Concentration up to 10 minutes",
  },
  sleep: {
    index: "sleep",
    name: "Sleep",
    time: "1 Action",
    range: 90,
    type: "utility",
    damage: null,
    duration: "1 Minute",
  },
  spareTheDying: {
    index: "spare-the-dying",
    name: "Spare the Dying",
    time: "1 Action",
    range: "Touch",
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  speakWithAnimals: {
    index: "speak-with-animals",
    name: "Speak With Animals",
    time: "1 Action",
    range: "Self",
    type: "utility",
    damage: null,
    duration: "Instant",
  },
  // tashasHideousLaughter: {

  //   name: "Tasha's Hideous Laughter",
  //   time: "1 Action",
  //   range: 30,
  //   type: "utility-save",
  //   save: "WIS",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  // tensersFloatingDisc: {
  //   name: "Tenser's Floating Disc",
  //   time: "1 Action",
  //   range: 30,
  //   type: "utility",
  //   damage: null,
  //   duration: "1 Hour",
  // },
  thaumaturgy: {
    index: "thaumaturgy",
    name: "Thaumaturgy",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 minute",
  },
  // thornWhip: {

  //   name: "Thorn Whip",
  //   time: "1 Action",
  //   range: 30,
  //   type: "attack",
  //   damage: 6,
  //   duration: "Instant",
  // },
  thunderWave: {
    index: "thunderwave",
    name: "Thunder Wave",
    time: "1 Bonus Action",
    range: "Self",
    type: "attack-save",
    save: "CON",
    damage: 16,
    duration: "Instant",
  },
  // thunderousSmite: {

  //   name: "Thunderous Smite",
  //   time: "1 Bonus Action",
  //   range: "Self",
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
  trueStrike: {
    index: "true-strike",
    name: "True Strike",
    time: "1 Action",
    range: 30,
    type: "utility",
    damage: null,
    duration: "Concentration up to 1 round",
  },
  unseenServant: {
    index: "unseen-servant",
    name: "Unseen Servant",
    time: "1 Action",
    range: 60,
    type: "utility",
    damage: null,
    duration: "1 Hour",
  },
  viciousMockery: {
    index: "vicious-mockery",
    name: "Vicious Mockery",
    time: "1 Action",
    range: 60,
    type: "attack-save",
    save: "WIS",
    damage: 4,
    duration: "Instant",
  },
  // witchBolt: {

  //   name: "Witch Bolt",
  //   time: "1 Action",
  //   range: 30,
  //   type: "attack",
  //   damage: 12,
  //   duration: "Concentration up to 1 minute",
  // },
  // wrathfulSmite: {
  //   name: "Wrathful Smite",
  //   time: "1 Bonus Action",
  //   range: "Self",
  //   type: "utility",
  //   damage: null,
  //   duration: "Concentration up to 1 minute",
  // },
};

export const classes = {
  barbarian: {
    name: "Barbarian",
    highestStat: "STR",
    starting_spell_options: {
      hasOptions: false,
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.battleaxe },
          { quantity: 1, choice: weapons.martial_weapons.flail },
          { quantity: 1, choice: weapons.martial_weapons.glaive },
          { quantity: 1, choice: weapons.martial_weapons.greataxe },
          { quantity: 1, choice: weapons.martial_weapons.halberd },
          { quantity: 1, choice: weapons.martial_weapons.lance },
          { quantity: 1, choice: weapons.martial_weapons.longsword },
          { quantity: 1, choice: weapons.martial_weapons.maul },
          { quantity: 1, choice: weapons.martial_weapons.morningstar },
          { quantity: 1, choice: weapons.martial_weapons.pike },
          { quantity: 1, choice: weapons.martial_weapons.rapier },
          { quantity: 1, choice: weapons.martial_weapons.scimitar },
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.martial_weapons.trident },
          { quantity: 1, choice: weapons.martial_weapons.warPick },
          { quantity: 1, choice: weapons.martial_weapons.warHammer },
          { quantity: 1, choice: weapons.martial_weapons.whip },
          { quantity: 1, choice: weapons.martial_ranged.blowgun },
          { quantity: 1, choice: weapons.martial_ranged.handCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.heavyCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.longbow },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 2, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
    ],
    hitDie: 12,
    sugg_background: "Outlander",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.animalHandling,
        skills.any.athletics,
        skills.any.intimidation,
        skills.any.nature,
        skills.any.perception,
        skills.any.perception,
        skills.any.survival,
      ],
    },
    savingThrows: ["STR", "CON"],
    startingArmorOptions: [],
  },

  bard: {
    name: "Bard",
    highestStat: "CHA",
    starting_spell_options: {
      hasOptions: true,
      cantrip_options: {
        choose: 2,
        from: [
          spells.bladeWard,
          spells.dancingLights.damage,
          spells.friends,
          spells.light,
          spells.mageHand,
          spells.mending,
          spells.message,
          spells.minorIllusion,
          spells.prestidigitation,
          spells.trueStrike,
          spells.viciousMockery,
        ],
      },
      spell_options: {
        choose: 4,
        from: [
          spells.animalFriendship,
          spells.bane,
          spells.charmPerson,
          spells.comprehendLanguages,
          spells.cureWounds,
          spells.detectMagic,
          spells.disguiseSelf,
          spells.dissonantWhispers,
          spells.faerieFire,
          spells.featherFall,
          spells.healingWord,
          spells.heroism,
          spells.identify,
          spells.illusoryScript,
          spells.longStrider,
          spells.silentImage,
          spells.sleep,
          spells.speakWithAnimals,
          spells.tashasHideousLaughter,
          spells.thunderWave,
          spells.unseenServant,
        ],
      },
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.rapier },
          { quantity: 1, choice: weapons.martial_weapons.longsword },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
    ],
    hitDie: 8,
    sugg_background: "Entertainer",
    skillProficiencies: {
      choose: 3,
      options: [
        { name: "Acrobatics" },
        { name: "Animal Handling" },
        { name: "Arcana" },
        { name: "Athletics" },
        { name: "Deception" },
        { name: "History" },
        { name: "Insight" },
        { name: "Intimidation" },
        { name: "Investigation" },
        { name: "Medicine" },
        { name: "Nature" },
        { name: "Perception" },
        { name: "Performance" },
        { name: "Persuasion" },
        { name: "Religion" },
        { name: "Sleight of Hand" },
        { name: "Stealth" },
        { name: "Survival" },
      ],
    },
    savingThrows: ["DEX", "CHA"],
    startingArmorOptions: [armors.leather],
  },
  cleric: {
    name: "Cleric",
    highestStat: "WIS",
    starting_spell_options: {
      hasOptions: true,
      cantrip_options: {
        choose: 3,
        from: [
          spells.guidance,
          spells.light,
          spells.mending,
          spells.resistance,
          spells.sacredFlame,
          spells.spareTheDying,
          spells.thaumaturgy,
        ],
      },
      spell_options: {
        choose: 2,
        from: [
          spells.bane,
          spells.bless,
          spells.command,
          spells.createOrDestroyWater,
          spells.cureWounds,
          spells.detectEvilAndGood,
          spells.detectMagic,
          spells.detectPoisonAndDisease,
          spells.guidingBolt,
          spells.healingWord,
          spells.inflictWounds,
          spells.protectionFromEvilAndGood,
          spells.purifyFoodAndDrink,
          spells.sanctuary,
          spells.shieldOfFaith,
        ],
      },
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.martial_weapons.warHammer },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
          { quantity: 1, choice: weapons.martial_ranged.handCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.heavyCrossbow },
        ],
      },
    ],
    hitDie: 8,
    sugg_background: "Acolyte",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.history,
        skills.any.insight,
        skills.any.medicine,
        skills.any.persuasion,
        skills.any.religion,
      ],
    },
    savingThrows: ["WIS", "CHA"],
    startingArmorOptions: [armors.scaleMail, armors.leather, armors.chainMail],
  },
  druid: {
    name: "Druid",
    highestStat: "WIS",
    starting_spell_options: {
      hasOptions: true,
      cantrip_options: {
        choose: 2,
        from: [
          spells.druidcraft,
          spells.guidance,
          spells.mending,
          spells.poisonSpray,
          spells.produceFlame,
          spells.resistance,
          spells.shillelagh,
          spells.thornWhip,
        ],
      },
      spell_options: {
        choose: 2,
        from: [
          spells.animalFriendship,
          spells.charmPerson,
          spells.createOrDestroyWater,
          spells.cureWounds,
          spells.detectMagic,
          spells.detectPoisonAndDisease,
          spells.entangle,
          spells.faerieFire,
          spells.fogCloud,
          spells.goodBerry,
          spells.healingWord,
          spells.jump,
          spells.longStrider,
          spells.purifyFoodAndDrink,
          spells.speakWithAnimals,
          spells.thunderWave,
        ],
      },
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.scimitar },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
    ],
    hitDie: 8,
    sugg_background: "Hermit",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.arcana,
        skills.any.animalHandling,
        skills.any.insight,
        skills.any.medicine,
        skills.any.nature,
        skills.any.perception,
        skills.any.religion,
        skills.any.survival,
      ],
    },
    savingThrows: ["INT", "WIS"],
    startingArmorOptions: [armors.leather],
  },
  fighter: {
    name: "Fighter",
    highestStat: "STR or DEX",
    starting_spell_options: {
      hasOptions: false,
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 2,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.battleaxe },
          { quantity: 1, choice: weapons.martial_weapons.flail },
          { quantity: 1, choice: weapons.martial_weapons.glaive },
          { quantity: 1, choice: weapons.martial_weapons.greataxe },
          { quantity: 1, choice: weapons.martial_weapons.halberd },
          { quantity: 1, choice: weapons.martial_weapons.lance },
          { quantity: 1, choice: weapons.martial_weapons.longsword },
          { quantity: 1, choice: weapons.martial_weapons.maul },
          { quantity: 1, choice: weapons.martial_weapons.morningstar },
          { quantity: 1, choice: weapons.martial_weapons.pike },
          { quantity: 1, choice: weapons.martial_weapons.rapier },
          { quantity: 1, choice: weapons.martial_weapons.scimitar },
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.martial_weapons.trident },
          { quantity: 1, choice: weapons.martial_weapons.warPick },
          { quantity: 1, choice: weapons.martial_weapons.warHammer },
          { quantity: 1, choice: weapons.martial_weapons.whip },
          { quantity: 1, choice: weapons.martial_ranged.blowgun },
          { quantity: 1, choice: weapons.martial_ranged.handCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.heavyCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.longbow },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 2, choice: weapons.simple_weapons.handAxe },
        ],
      },
    ],
    hitDie: 10,
    sugg_background: "Soldier",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.acrobatics,
        skills.any.animalHandling,
        skills.any.athletics,
        skills.any.history,
        skills.any.insight,
        skills.any.intimidation,
        skills.any.perception,
        skills.any.survival,
      ],
    },
    savingThrows: ["STR", "CON"],
    startingArmorOptions: [armors.chainMail, armors.leather],
  },

  monk: {
    name: "Monk",
    highestStat: "DEX and WIS",
    hitDie: 8,
    starting_spell_options: {
      hasOptions: false,
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
    ],
    sugg_background: "Hermit",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.acrobatics,
        skills.any.athletics,
        skills.any.history,
        skills.any.insight,
        skills.any.religion,
        skills.any.stealth,
      ],
    },
    savingThrows: ["STR", "DEX"],
    startingArmorOptions: [],
  },
  paladin: {
    name: "Paladin",
    highestStat: "STE and WIS",
    starting_spell_options: {
      hasOptions: false,
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 2,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.battleaxe },
          { quantity: 1, choice: weapons.martial_weapons.flail },
          { quantity: 1, choice: weapons.martial_weapons.glaive },
          { quantity: 1, choice: weapons.martial_weapons.greataxe },
          { quantity: 1, choice: weapons.martial_weapons.halberd },
          { quantity: 1, choice: weapons.martial_weapons.lance },
          { quantity: 1, choice: weapons.martial_weapons.longsword },
          { quantity: 1, choice: weapons.martial_weapons.maul },
          { quantity: 1, choice: weapons.martial_weapons.morningstar },
          { quantity: 1, choice: weapons.martial_weapons.pike },
          { quantity: 1, choice: weapons.martial_weapons.rapier },
          { quantity: 1, choice: weapons.martial_weapons.scimitar },
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.martial_weapons.trident },
          { quantity: 1, choice: weapons.martial_weapons.warPick },
          { quantity: 1, choice: weapons.martial_weapons.warHammer },
          { quantity: 1, choice: weapons.martial_weapons.whip },
          { quantity: 1, choice: weapons.martial_ranged.blowgun },
          { quantity: 1, choice: weapons.martial_ranged.handCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.heavyCrossbow },
          { quantity: 1, choice: weapons.martial_ranged.longbow },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 5, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
        ],
      },
    ],
    hitDie: 10,
    sugg_background: "Noble",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.athletics,
        skills.any.insight,
        skills.any.intimidation,
        skills.any.medicine,
        skills.any.persuasion,
        skills.any.religion,
      ],
    },
    savingThrows: ["WIS", "CHA"],
    startingArmorOptions: [armors.chainMail],
  },
  ranger: {
    name: "Ranger",
    highestStat: "DEX and WIS",
    starting_spell_options: {
      hasOptions: false,
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 2,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
        ],
      },
    ],
    hitDie: 10,
    sugg_background: "Outlander",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.animalHandling,
        skills.any.athletics,
        skills.any.insight,
        skills.any.investigation,
        skills.any.nature,
        skills.any.perception,
        skills.any.stealth,
        skills.any.survival,
      ],
    },
    savingThrows: ["STR", "DEX"],
    startingArmorOptions: [armors.scaleMail, armors.leather],
  },
  rogue: {
    name: "Rogue",
    highestStat: "DEX",
    starting_spell_options: {
      hasOptions: false,
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.martial_weapons.rapier },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.martial_weapons.shortsword },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
        ],
      },
    ],
    hitDie: 8,
    sugg_background: "Charlatan",
    skillProficiencies: {
      choose: 4,
      options: [
        skills.any.acrobatics,
        skills.any.athletics,
        skills.any.deception,
        skills.any.insight,
        skills.any.intimidation,
        skills.any.investigation,
        skills.any.perception,
        skills.any.performance,
        skills.any.persuasion,
        skills.any.sleightOfHand,
        skills.any.stealth,
      ],
    },
    savingThrows: ["DEX", "INT"],
    startingArmorOptions: [armors.leather],
  },
  sorcerer: {
    name: "Sorcerer",
    highestStat: "CHA",
    starting_spell_options: {
      hasOptions: true,
      cantrip_options: {
        choose: 4,
        from: [
          spells.acidSplash,
          spells.bladeWard,
          spells.chillTouch,
          spells.dancingLights,
          spells.fireBolt,
          spells.friends,
          spells.light,
          spells.mageHand,
          spells.mending,
          spells.message,
          spells.minorIllusion,
          spells.poisonSpray,
          spells.rayOfFrost,
          spells.shockingGrasp,
          spells.trueStrike,
        ],
      },
      spell_options: {
        choose: 2,
        from: [
          spells.burningHands,
          spells.charmPerson,
          spells.chromaticOrb,
          spells.comprehendLanguages,
          spells.detectMagic,
          spells.disguiseSelf,
          spells.expeditiousRetreat,
          spells.falseLife,
          spells.featherFall,
          spells.fogCloud,
          spells.jump,
          spells.mageArmor,
          spells.magicMissile,
          spells.rayOfSickness,
          spells.shield,
          spells.silentImage,
          spells.sleep,
          spells.thunderWave,
          spells.witchBolt,
        ],
      },
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
    ],
    hitDie: 6,
    sugg_background: "Hermit",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.arcana,
        skills.any.deception,
        skills.any.insight,
        skills.any.intimidation,
        skills.any.persuasion,
        skills.any.religion,
      ],
    },
    savingThrows: ["CON", "CHA"],
    startingArmorOptions: [],
  },
  warlock: {
    name: "Warlock",
    highestStat: "CHA",
    starting_spell_options: {
      hasOptions: true,
      cantrip_options: {
        choose: 2,
        from: [
          spells.bladeWard,
          spells.chillTouch,
          spells.eldritchBlast,
          spella.friends,
          spells.mageHand,
          spells.minorIllusion,
          spells.poisonSpray,
          spells.prestidigitation,
          spells.trueStrike,
        ],
      },
      spell_options: {
        choose: 2,
        from: [
          spells.armorOfAgathys,
          spells.armsOfHadar,
          spells.charmPerson,
          spells.comprehendLanguages,
          spells.expeditiousRetreat,
          spells.hellishRebuke,
          spells.hex,
          spells.illusoryScript,
          spells.protectionFromEvilAndGood,
          spells.unseenServant,
          spells.witchBolt,
        ],
      },
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
      {
        option: 2,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_ranged.lightCrossbow },
          { quantity: 1, choice: weapons.simple_weapons.club },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
          { quantity: 1, choice: weapons.simple_weapons.greatClub },
          { quantity: 1, choice: weapons.simple_weapons.handAxe },
          { quantity: 1, choice: weapons.simple_weapons.javelin },
          { quantity: 1, choice: weapons.simple_weapons.lightHammer },
          { quantity: 1, choice: weapons.simple_weapons.mace },
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.sickle },
          { quantity: 1, choice: weapons.simple_weapons.spear },
          { quantity: 1, choice: weapons.simple_ranged.dart },
          { quantity: 1, choice: weapons.simple_ranged.shortbow },
          { quantity: 1, choice: weapons.simple_ranged.sling },
        ],
      },
    ],
    hitDie: 6,
    sugg_background: "Charlatan",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.arcana,
        skills.any.deception,
        skills.any.history,
        skills.any.intimidation,
        skills.any.investigation,
        skills.any.nature,
        skills.any.religion,
      ],
    },
    savingThrows: ["WIS", "CHA"],
    startingArmorOptions: [armors.leather],
  },
  wizard: {
    name: "Wizard",
    highestStat: "INT",
    starting_spell_options: {
      hasOptions: true,
      cantrip_options: {
        choose: 3,
        from: [
          spells.acidSplash,
          spells.bladeWard,
          spells.chillTouch,
          spells.dancingLights,
          spells.fireBolt,
          spells.friends,
          spells.light,
          spells.mageHand,
          spells.mending,
          spells.message,
          spells.minorIllusion,
          spells.poisonSpray,
          spells.prestidigitation,
          spells.rayOfFrost,
          spells.shockingGrasp,
          spells.trueStrike,
        ],
      },
      spell_options: {
        choose: 6,
        from: [
          spells.alarm,
          spells.burningHands,
          spells.charmPerson,
          spells.chromaticOrb,
          spells.colorSpray,
          spells.comprehendLanguages,
          spells.detectMagic,
          spells.disguiseSelf,
          spells.expeditiousRetreat,
          spells.falseLife,
          spells.featherFall,
          spells.findFamiliar,
          spells.fogCloud,
          spells.grease,
          spells.identify,
          spells.illusoryScript,
          spells.jump,
          spells.longStrider,
          spells.mageArmor,
          spells.magicMissile,
          spells.protectionFromEvilAndGood,
          spells.rayOfSickness,
          spells.shield,
          spells.tashasHideousLaughter,
          spells.tensersFloatingDisc,
          spells.thunderWave,
          spells.unseenServant,
          spells.witchBolt,
        ],
      },
    },
    starting_weap_options: [
      {
        option: 1,
        choose: 1,
        from: [
          { quantity: 1, choice: weapons.simple_weapons.quarterstaff },
          { quantity: 1, choice: weapons.simple_weapons.dagger },
        ],
      },
    ],
    hitDie: 6,
    sugg_background: "Sage",
    skillProficiencies: {
      choose: 2,
      options: [
        skills.any.arcana,
        skills.any.history,
        skills.any.insight,
        skills.any.investigation,
        skills.any.medicine,
        skills.any.religion,
      ],
    },
    savingThrows: ["INT", "WIS"],
    startingArmorOptions: [],
  },
};
